### ISSUE TITLE
v1.0.7 Follow-up Question.

### ISSUE THREAD

**Issue by litanbid** [LeiQiaoZhi/Easy-Text-Effects-for-Unity#17]
Hello,
The issue I previously mentioned has been resolved, and the package is now correctly displayed on OpenUPM.
However, it seems that version 1.0.7 is not based on the 1.0.6 tag. Is that correct?
Also, the StartManualEffect method now has a return type, which makes it unusable with UnityEvent.
Could you please confirm whether this change was intentional?
Thank you very much.

**Comment by LeiQiaoZhi** [comment]
Thanks for letting me know, the return types were added in a previous pr (commit fad3005ef6b7e262048ece96f4e47bef73cf9970). I overlooked and didn't think of this side effect. The return type should not be added. I pushed a fix just now to address this.

**Comment by LeiQiaoZhi** [comment]
> However, it seems that version 1.0.7 is not based on the 1.0.6 tag. Is that correct?

Could you please elaborate on this? Based on the git history, v1.0.7 is built on top of v1.0.6. Is it a OpenUPM-related issue?

**Comment by LeiQiaoZhi** [comment]
I think I understood the problem now. The return value was indeed added in v1.0.6, but because I forgot to update the package.json to match the version number, I suspect openupm didn't pickup the changes. I fixed the return type and along with another bug fix, v1.0.8 should no longer have this issue. Could you please try updating to v1.0.8 and let me know if the return value issue is fixed now? thanks

**Comment by litanbid** [comment]
Hello,
I was only able to check this now due to other work.
We had been using version 1.0.5 previously, and after updating the package to 1.0.8, there were no compilation errors.
However, we did not perform any other migration steps, and perhaps because of that, we've noticed that existing composite effects running as OneTime do not persist and instead revert to their initial state.
For now, we’ll need to continue using the previous version.
It’s possible that we may have used it incorrectly on our end, so we’ll review it again when we have more time.
Thank you.

**Comment by LeiQiaoZhi** [comment]
Thanks for your response. I'll look into the composite effect issue.
